version: '3.8'

services:

  heating-controller-app:
    build:
      context: ./
      target: prod
    links:
      - redis
      - mosquitto
    volumes:
      - .:/src
    command: npm run start
    ports:
      - '3000:3000'
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=prod
      - PORT=3000
    restart: on-failure
  redis:
    image: redis:latest
    container_name: cache
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - '1883:1883'
volumes:
  redis-data:
  redis-conf: